bot:
  messages_path: config/messages.yaml
  commands_path: config/commands.yaml
  timers:
    task_poll_time: 60
  time:
    opening_hour: 10
    closing_hour: 18
    local_tz: 'Australia/Sydney'
    escalation_time_mins: 2
    backoff_time_hrs: 21

database:
  provider: sql
  sql:
    user: root
    password: password
    host: 127.0.0.1
    db: securitybot
    queries_path: config/queries/mysql.yaml

user: 
  fetcher:
    name: ldap
    options:
      username: 'user'
      password: changeme
      host: ldap.example.com

auth:
  provider: okta
  reauth_time: 3600
  auth_attrib: displayname
  nullauth:
  okta:
    api_token: 'TOKEN'
    base_url: 'https://XXXXXX.okta.com'
  duo:
    ikey: 'IKEY'
    skey: 'SKEY'
    endpoint: 'XXXXXX.duosecurity.com'

chat:
  provider: slack
  slack:
    username: 'CyberBot'
    token: 'TOKEN'
    reporting_channel: 'CXXXXXXXX'
    icon_url: 'https://dl.dropboxusercontent.com/s/t01pwfrqzbz3gzu/securitybot.png'

debug:
  level: 'debug'

