bot:
  # Paramaters of our bot
  messages_path: config/messages.yaml
  commands_path: config/commands.yaml
  timers:
    task_poll_time: 60
  time:
    opening_hour: 10
    closing_hour: 18
    local_tz: 'Australia/Sydney'
    escalation_time_mins: 2
    backoff_time_hrs: 21

secretsmgmt:
  # How secrets will be managed, and which secrets to use
  # Supported: Hashicorp Vault (vault), AWS Secrets Manager (awssecretsmanager)
  provider: vault
  secrets:
    chat:
      slack:
        - token
    database:
      mysql:
        - user
        - password
    auth:
      okta:
        - token
      duo:
        - ikey
        - skey

  vault:
    token_env: 'VAULT_TOKEN_ID'
    url: 'http://127.0.0.1:8200'
  awssecretsmanager:

database:
  # How state will be maintained
  # Supported: MySQL (mysql), AWS SimpleDB (awssimpledb)
  provider: awssimpledb
  mysql:
    host: 127.0.0.1
    db: securitybot
    queries_path: config/queries/mysql.yaml
  awssimpledb:
    domain_prefix: secbot

auth:
  # How we will use MFA to authenticate users
  # Supported: Okta Push (okta), Duo (duo), Dummy (nullauth)
  provider: nullauth
  reauth_time: 3600
  auth_attrib: displayname
  nullauth:
  okta:
    base_url: 'https://XXXXXX.okta.com'
  duo:
    endpoint: 'XXXXXX.duosecurity.com'

chat:
  # The chat platform the bot will run on, and talk to users
  # Supported: Slack (slack)
  provider: slack
  slack:
    username: 'CyberBot'
    reporting_channel: 'Cxxxxxxxxxx'
    icon_url: 'https://dl.dropboxusercontent.com/s/t01pwfrqzbz3gzu/securitybot.png'

user: 
  fetcher:
    name: ldap
    options:
      username: 'user'
      password: changeme
      host: ldap.example.com

debug:
  level: 'debug'

